# Generated by Django 5.0.3 on 2024-04-12 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temp_day', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temp_night', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.JSONField()),
                ('feels_like', models.JSONField()),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('weather', models.CharField(max_length=255)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_deg', models.IntegerField()),
                ('cloudiness', models.IntegerField()),
                ('rain', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='weather.weathersummary')),
            ],
        ),
    ]
