# Generated by Django 5.0.3 on 2024-04-12 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_maps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waypoint',
            name='votes',
        ),
        migrations.AddField(
            model_name='waypoint',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='resource_type',
            field=models.CharField(default='not specified', max_length=50),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_date', models.DateTimeField(auto_now_add=True)),
                ('vote', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='resource_maps.waypoint')),
            ],
            options={
                'unique_together': {('waypoint', 'user', 'vote_date')},
            },
        ),
    ]
