# Generated by Django 5.0.3 on 2024-04-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_maps', '0003_resourcecategory_remove_waypoint_resource_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
