# Generated by Django 5.0.3 on 2024-04-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_maps', '0004_alter_waypoint_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='votes_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='votes_yes',
            field=models.IntegerField(default=0),
        ),
    ]
